import java.util.Scanner;

public class ExceptionTest {
	public static void main(String[] args) {
		Scanner scan = new Scanner(System.in);
		System.out.print("분자 : ");
		int num1 = scan.nextInt();
		System.out.print("분모 : ");
		int num2 = scan.nextInt();
		
		try {
			int result = num1 / num2;	
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		
	}
}
